# Generated by Django 3.2.6 on 2021-08-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags_info',
            name='task_id',
            field=models.IntegerField(default=0),
        ),
    ]
