# Generated by Django 3.2.6 on 2021-08-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tags_info_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags_info',
            name='task_id',
            field=models.CharField(max_length=255),
        ),
    ]
